### ISSUE TITLE
doesn't work when edit vim file

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc-neco#1]
1. works:

```bash
nvim test.vim
```

2. doesn't work:

```bash
nvim
:e test.vim
```

**Comment by iamcco** [comment]
this is the record:
https://asciinema.org/a/I13hO2ETAqA4SGr6iXxdtfwVb

**Comment by chemzqm** [comment]
I don't have this issue.
I thinks it's caused by lazy load, coc have to watch for `rtp` change to fix this problem.

**Comment by iamcco** [comment]
yep, it works after remove lazy load.

**Comment by ahmedelgabri** [comment]
For me it doesn't work at all & not lazy loading any of the plugins. I'm using [`minpac`](https://github.com/k-takata/minpac) & 

Here is how I'm installing the plugins [config](https://github.com/ahmedelgabri/dotfiles/blob/cd51f3ac34d111afaa5bbb5ad61e64cd0b6853e0/files/.vim/autoload/plugins.vim#L78-L80) & here is my `coc` [config](https://github.com/ahmedelgabri/dotfiles/blob/46c90c48a1b1e375b64db831d53e000303540a83/files/.vim/after/plugin/coc.vim)
