### ISSUE TITLE
Support for variables?

### ISSUE THREAD

**Issue by mikew** [neoclide/coc-neco#3]
Kicking the tires with coc, coming from ale + asyncomplete.

Using neco in asyncomplete, you are able to see variables in addition to functions. ie, simply typing:

```viml
echo g:
```

will show you all global variables. Is that info intentionally stripped from coc-neco?

**Comment by chemzqm** [comment]
You can try out https://github.com/iamcco/coc-vimlsp, which works better.

**Comment by mikew** [comment]
coc-vimlsp it is.
